name: geog0111
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
#  - mkdocs
  - sphinx
  - pip
  - pip:
#    - mkdocs-jupyter
#    - jupyter_contrib_nbextensions
#    - mknotebooks
#    - mkdocs-material
#    - mkdocs-exclude
#    - mkdocs-git-revision-date-localized-plugin
