name: geog0111
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - pip:
#    - jupyter_contrib_nbextensions
#    - mkdocs
    - sphinx
#    - mkdocs-jupyter
#    - mknotebooks
#    - mkdocs-exclude
#    - mkdocs-git-revision-date-localized-plugin
    - recommonmark
    - sphinx-markdown-tables
    - sphinx-typlog-theme
#    - mkdocs-rtd-dropdown
#    - mkdocs-material
