extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/prof_plewis
  - icon: fontawesome/brands/github
    link: https://github.com/UCL-EO/Workshop2022
extra_javascript:
- javascripts/config.js
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
nav:
- Introduction: index.md
- Solar Radiation:
  - Solar Practical: 005_Solar_Practical.md
plugins:
- git-revision-date-localized
- exclude:
    glob:
    - '*blank.tif'
    - '*.pyc'
    - python/__pycache__/*
    - work/*
    - __pycache__
    - '*.bin'
    - '*.hdf'
    - '*.store'
    - '*.nc'
    - '*.zip'
    - '*.npz'
    - data/ucl/*
    - '*.vrt'
repo_url: https://github.com/UCL-EO/Workshop2022
site_author: Prof P. Lewis
site_name: Workshop2022
theme:
  favicon: figures/ucl.png
  logo: figures/ucl.png
  name: material
